# Generated by Django 2.2.2 on 2019-06-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='memo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
